### ISSUE TITLE
Deploy the Cloud stack to sense-mon.es.net and testing

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rtmon#22]
@ZhenboYan Can you add pointers to the documentation for the deployment? 

I want to use this issue as reference and notes for future deployment.

**Comment by ZhenboYan** [comment]
Deployment Documentation: https://github.com/esnet/sense-rtmon/wiki/Deployment-Documentation

**Comment by xi-yang** [comment]
@ZhenboYan Here is a list some issues to fix from my first attempt of installing the Cloud stack.

- [ ] 1. Let's encrypt cert failed to generate. In many hosts with Docker installed, the host firewall will not have port 80 open unless a container is mapped with port 80. So instead of using certbot from host, run a certbot container instead. 

Try this below in `certify.sh` script.
```
docker run --rm -it -v /etc/letsencrypt:/etc/letsencrypt -p 80:80 certbot/certbot certonly \
             --standalone -n --agree-tos \
            --register-unsafely-without-email \
            --domains $domain
```

- [ ] 2. For host with existing certificate (sense-mon.es.net has got InCommon cert under `/etc/pki/tls/`), provide an option to use the existing cert. 

- [ ] 3. The prompt `Enter configuration file [config.yml (Enter)]:` is unclear. When I run install from `/opt/sense-rtmon/cloud`, does this refer to `/opt/sense-rtmon/config/config.yml`? There should also be an explanation of customizing the config.yml file in both `Site` and `Cloud` install sections. 
- [ ]

**Comment by xi-yang** [comment]
These sections in config.yml is confusing. Why do we need host configs for Cloud stack? Is that because we are pulling from host node-exporter. Can we do push from the hosts?

```
# Host 1: BOTH (all needed)
hostA:
  IP: 198.32.43.16
  interfaceName: 'ens2f0np0.1000'
  interfaceIP: '10.10.100.1'
  nodeName: 'sdn-dtn-2-10.ultralight.org'
  vlan: 1000
  nodeExporterPort: 9100
  switchPort:
    ifName: 'hundredGigE 1/27'
    ifVlan: 'Vlan 1000'

# Host 2 BOTH (all needed)
hostB:
  IP: 198.32.43.15
  interfaceName: 'ens2f0.1000'
  interfaceIP: '10.10.100.2'
  nodeName: 'sdn-dtn-2-11.ultralight.org'
  vlan: 1000
  nodeExporterPort: 9100
  switchPort:
    ifName: 'hundredGigE 1/31'
    ifVlan: 'Vlan 1000'
```
