### ISSUE TITLE
Portability Testing Across Different Environments

### ISSUE THREAD

**Issue by sunami09** [esnet/sense-rtmon#70]
# Portability Testing Across Different Environments

The purpose of this document is to outline the steps for testing the codebase across different environments to ensure its portability and functionality.

## Objective

The goal is to verify that the application functions correctly across various systems and configurations. This includes successful compilation, application startup, and operation.

## Test Procedure

- [x] **Clone Repository**
  - Ensure that the repository is cloned properly on the target machine.
  - https://github.com/esnet/sense-rtmon/issues/70#issuecomment-1933268868

- [x] **Fill out Configuration**
  - Complete the necessary configuration in the `config.yaml` file to tailor the application to the environment.
  - https://github.com/esnet/sense-rtmon/issues/70#issuecomment-1933322150

- [x] #71
  - Execute `install.sh` to install any dependencies and set up the environment.
  - https://github.com/esnet/sense-rtmon/issues/71#issuecomment-1933554555

- [x] #72
  - Run `start.sh` to initiate the application process.
  - Need suggestions: https://github.com/esnet/sense-rtmon/issues/72#issuecomment-1933592097 @xi-yang @PannuMuthu 
  - https://github.com/esnet/sense-rtmon/issues/72#issuecomment-1933605729

- [x] **Set up Grafana Dashboard**
  - Access the Grafana dashboard and configure the correct data source to visualize the application metrics.
  - https://github.com/esnet/sense-rtmon/issues/70#issuecomment-1933617719

- [x] #73
  - Perform an update using `update.sh` to start the main loop container.

- [x] **Examine Dashboard**
  - Review the Grafana dashboard to confirm that metrics are being reported correctly and the application is functioning as expected.

**Comment by sunami09** [comment]
## Cloned Repo

Successfully cloned the repository and here is the current state:

![Cloned Repository Screenshot](https://github.com/esnet/sense-rtmon/assets/66564001/af7c7ca8-098a-4661-ac84-c4bff75b19e2)

**Comment by sunami09** [comment]
## Configuration Completion

The `config.yaml` file has been updated with the necessary parameters, tailoring the application to meet the operational requirements effectively.

### Configuration Details

Below is the detailed configuration that has been applied:

```yaml
hostIP: 100.26.56.42

ssl_certificate_key: '/root/sense-o.es.net-ssl/sense-o.key'
ssl_certificate: '/root/sense-o.es.net-ssl/sense-o.crt'
grafana_host: 'http://dev2.virnao.com:3000'
pushgateway: 'http://dev2.virnao.com:9091'
grafana_username: 'admin'
grafana_password: 'admin'
grafana_api_token: "Bearer API [HIDDEN] "
siterm_url_map:
  "urn:ogf:network:nrp-nautilus.io:2020": https://sense-prpdev-fe.sdn-lb.ultralight.org/T2_US_SDSC/sitefe/json/frontend
  "urn:ogf:network:ultralight.org:2013": https://sense-caltech-fe.sdn-lb.ultralight.org/T2_US_Caltech_Test/sitefe/json/frontend
  "urn:ogf:network:sc-test.cenic.net:2020": https://sense-ladowntown-fe.sdn-lb.ultralight.org/NRM_CENIC/sitefe/json/frontend
```
